/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManualSimulator.java
 *
 * Created on May 24, 2014, 8:13:36 PM
 */

package trainsimulator;

import java.nio.ByteBuffer;

/**
 *
 * @author I14746
 */
public class ManualSimulator extends javax.swing.JPanel {

    private DataFrame CurrentFrame;
    private int StartStop = 0;
    private static byte[] Config = new byte[]{0x3,0x0};
    /** Creates new form ManualSimulator */
    public ManualSimulator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManualPanel = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        BBtn = new javax.swing.JToggleButton();
        ABBtn = new javax.swing.JToggleButton();
        ABtn = new javax.swing.JToggleButton();
        jPanel23 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        DBtn = new javax.swing.JToggleButton();
        CDBtn = new javax.swing.JToggleButton();
        CBtn = new javax.swing.JToggleButton();

        setName("Form"); // NOI18N

        ManualPanel.setName("ManualPanel"); // NOI18N
        ManualPanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel22.setName("jPanel22"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(trainsimulator.TrainSimulatorApp.class).getContext().getResourceMap(ManualSimulator.class);
        jLabel54.setFont(resourceMap.getFont("jLabel54.font")); // NOI18N
        jLabel54.setText(resourceMap.getString("jLabel54.text")); // NOI18N
        jLabel54.setName("jLabel54"); // NOI18N

        jSeparator11.setName("jSeparator11"); // NOI18N

        BBtn.setFont(resourceMap.getFont("jLabel54.font")); // NOI18N
        BBtn.setText(resourceMap.getString("BBtn.text")); // NOI18N
        BBtn.setName("BBtn"); // NOI18N
        BBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBtnActionPerformed(evt);
            }
        });

        ABBtn.setFont(resourceMap.getFont("jLabel54.font")); // NOI18N
        ABBtn.setText(resourceMap.getString("ABBtn.text")); // NOI18N
        ABBtn.setName("ABBtn"); // NOI18N
        ABBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABBtnActionPerformed(evt);
            }
        });

        ABtn.setFont(resourceMap.getFont("jLabel54.font")); // NOI18N
        ABtn.setText(resourceMap.getString("ABtn.text")); // NOI18N
        ABtn.setName("ABtn"); // NOI18N
        ABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ABBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel22Layout.createSequentialGroup()
                            .addComponent(ABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BBtn))))
                .addContainerGap())
        );

        jPanel22Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ABtn, BBtn});

        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ABtn)
                    .addComponent(BBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ABBtn)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        ManualPanel.add(jPanel22);

        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.setName("jPanel23"); // NOI18N

        jLabel56.setFont(resourceMap.getFont("jLabel54.font")); // NOI18N
        jLabel56.setText(resourceMap.getString("jLabel56.text")); // NOI18N
        jLabel56.setName("jLabel56"); // NOI18N

        jSeparator12.setName("jSeparator12"); // NOI18N

        DBtn.setFont(resourceMap.getFont("jLabel54.font")); // NOI18N
        DBtn.setText(resourceMap.getString("DBtn.text")); // NOI18N
        DBtn.setName("DBtn"); // NOI18N
        DBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBtnActionPerformed(evt);
            }
        });

        CDBtn.setFont(resourceMap.getFont("jLabel54.font")); // NOI18N
        CDBtn.setText(resourceMap.getString("CDBtn.text")); // NOI18N
        CDBtn.setName("CDBtn"); // NOI18N
        CDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDBtnActionPerformed(evt);
            }
        });

        CBtn.setFont(resourceMap.getFont("jLabel54.font")); // NOI18N
        CBtn.setText(resourceMap.getString("CBtn.text")); // NOI18N
        CBtn.setName("CBtn"); // NOI18N
        CBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CDBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel23Layout.createSequentialGroup()
                            .addComponent(CBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DBtn))))
                .addContainerGap())
        );

        jPanel23Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CBtn, DBtn});

        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBtn)
                    .addComponent(DBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CDBtn)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        ManualPanel.add(jPanel23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(ManualPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(ManualPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABtnActionPerformed
      ExecuteEntrySide();
    }//GEN-LAST:event_ABtnActionPerformed

    private void BBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBtnActionPerformed
       ExecuteEntrySide();
    }//GEN-LAST:event_BBtnActionPerformed

    private void ABBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABBtnActionPerformed
        ABtn.setSelected(ABBtn.isSelected());
        BBtn.setSelected(ABBtn.isSelected());
        ExecuteEntrySide();
    }//GEN-LAST:event_ABBtnActionPerformed

    private void CBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBtnActionPerformed
       ExecuteExitSide();
    }//GEN-LAST:event_CBtnActionPerformed

    private void DBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBtnActionPerformed
       ExecuteExitSide();
    }//GEN-LAST:event_DBtnActionPerformed

    private void CDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDBtnActionPerformed
        CBtn.setSelected(CDBtn.isSelected());
        DBtn.setSelected(CDBtn.isSelected());
        ExecuteExitSide();
    }//GEN-LAST:event_CDBtnActionPerformed

    private void ExecuteEntrySide(){
        if(ABtn.isSelected() && BBtn.isSelected()){
            ABBtn.setSelected(true);
        }else if(ABtn.isSelected() == false && BBtn.isSelected() == false){
            ABBtn.setSelected(false);
        }
        DataFrame df = new DataFrame();
        df.Command = Config;
        df.Payload.speed = getEntrySwitchState();
        df.Payload.configuration = (byte) 0x1;
        df.Payload.auto_manual = (byte) 0x2;
        CurrentFrame = df;
        Thread te = new Thread(new Runnable() {
        public void run()
        {
            TrainSimulatorApp.getApplication().getView().SendPacketRecieveResponse(CurrentFrame);
        }
        });
        te.start();
    }
    
    private void ExecuteExitSide(){
        if(CBtn.isSelected() && DBtn.isSelected()){
            CDBtn.setSelected(true);
        }else if(CBtn.isSelected() == false && DBtn.isSelected() == false){
            CDBtn.setSelected(false);
        }
        DataFrame df = new DataFrame();
        df.Command = Config;
        df.Payload.speed = getExitSwitchState();
        df.Payload.configuration = (byte) 0x2;
        df.Payload.auto_manual = (byte) 0x2;
        CurrentFrame = df;
        Thread te = new Thread(new Runnable() {
        public void run()
        {
            TrainSimulatorApp.getApplication().getView().SendPacketRecieveResponse(CurrentFrame);
        }
        });
        te.start();
    }
    
    private int getEntrySwitchState(){
        int State = 0;
        byte[] temp = new byte[4];
        if(ABtn.isSelected()){
            temp[3] = 1;
        }
        if(BBtn.isSelected()){
            temp[2] = 1;
        }
        if(ABBtn.isSelected()){
            temp[1] = 1;
        }
        State = ByteBuffer.wrap(temp).getInt();
        return State;
    }
    
    private int getExitSwitchState(){
        int State = 0;
        byte[] temp = new byte[4];
        if(CBtn.isSelected()){
            temp[3] = 1;
        }
        if(DBtn.isSelected()){
            temp[2] = 1;
        }
        if(CDBtn.isSelected()){
            temp[1] = 1;
        }
        State = ByteBuffer.wrap(temp).getInt();
        return State;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ABBtn;
    private javax.swing.JToggleButton ABtn;
    private javax.swing.JToggleButton BBtn;
    private javax.swing.JToggleButton CBtn;
    private javax.swing.JToggleButton CDBtn;
    private javax.swing.JToggleButton DBtn;
    private javax.swing.JPanel ManualPanel;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    // End of variables declaration//GEN-END:variables

}
