/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimulatorPanel.java
 *
 * Created on May 24, 2014, 8:03:10 PM
 */

package trainsimulator;

import java.io.IOException;
import java.util.Date;
import trainsimulator.common.SharedData;

/**
 *
 * @author I14746
 */
public class SimulatorPanel extends javax.swing.JPanel {

    private int StartStop = 0; //start =0; stop =1;
    private static byte[] Config = new byte[]{0x3,0x0};
    
    private SerialHelper sh = new SerialHelper();
    SharedData shareddata = SharedData.getSingletonObject();
    boolean dataRecievedFlag = false;
    private String headerOfPanel;
    DataFrame CurrentFrame;
    
    /** Creates new form SimulatorPanel */
    public SimulatorPanel(String header) {
        initComponents();
        entryType.setText(header);
        this.headerOfPanel = header;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel24 = new javax.swing.JPanel();
        BtnStart = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        TxtCount = new javax.swing.JTextField();
        TxtSpeed = new javax.swing.JTextField();
        BtnStop = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        entryType = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jPanel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel24.setName("jPanel24"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(trainsimulator.TrainSimulatorApp.class).getContext().getResourceMap(SimulatorPanel.class);
        BtnStart.setBackground(resourceMap.getColor("BtnStart.background")); // NOI18N
        BtnStart.setFont(resourceMap.getFont("BtnStart.font")); // NOI18N
        BtnStart.setForeground(resourceMap.getColor("BtnStart.foreground")); // NOI18N
        BtnStart.setText(resourceMap.getString("BtnStart.text")); // NOI18N
        BtnStart.setName("BtnStart"); // NOI18N
        BtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStartActionPerformed(evt);
            }
        });

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText(resourceMap.getString("jLabel52.text")); // NOI18N
        jLabel52.setName("jLabel52"); // NOI18N

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText(resourceMap.getString("jLabel53.text")); // NOI18N
        jLabel53.setName("jLabel53"); // NOI18N

        TxtCount.setText(resourceMap.getString("TxtCount.text")); // NOI18N
        TxtCount.setName("TxtCount"); // NOI18N

        TxtSpeed.setText(resourceMap.getString("TxtSpeed.text")); // NOI18N
        TxtSpeed.setName("TxtSpeed"); // NOI18N

        BtnStop.setBackground(resourceMap.getColor("BtnStop.background")); // NOI18N
        BtnStop.setFont(resourceMap.getFont("BtnStart.font")); // NOI18N
        BtnStop.setForeground(resourceMap.getColor("jButton27.foreground")); // NOI18N
        BtnStop.setText(resourceMap.getString("BtnStop.text")); // NOI18N
        BtnStop.setName("BtnStop"); // NOI18N
        BtnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStopActionPerformed(evt);
            }
        });

        jSeparator13.setName("jSeparator13"); // NOI18N

        entryType.setFont(resourceMap.getFont("entryType.font")); // NOI18N
        entryType.setText(resourceMap.getString("entryType.text")); // NOI18N
        entryType.setName("entryType"); // NOI18N

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entryType, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtCount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(TxtSpeed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(BtnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnStop, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel24Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnStart, BtnStop});

        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(entryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(TxtSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(TxtCount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BtnStart)
                    .addComponent(BtnStop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel24Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnStart, BtnStop});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStartActionPerformed
        //System.out.println("Start " + entryType.getText());
        StartStop = 1;
        DataFrame df = new DataFrame();
        df.Command = Config;
        df.Payload.speed = Integer.parseInt(TxtSpeed.getText());
        df.Payload.speed = df.Payload.speed /10; // this is beacuse the speed the firmware expects is only from 1-30. so UI will divide it by 10.
        df.Payload.count = Integer.parseInt(TxtCount.getText());
        df.Payload.configuration = (byte) getConfig();
        df.Payload.start_stop = (byte) StartStop;
        CurrentFrame = df;
        Thread te = new Thread(new Runnable() {
        public void run()
        {
            TrainSimulatorApp.getApplication().getView().SendPacketRecieveResponse(CurrentFrame);
            TrainSimulatorApp.getApplication().getView().Initialise_FWD_counter(getConfig());            
        }
        });
        te.start();
    }//GEN-LAST:event_BtnStartActionPerformed

    private void BtnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStopActionPerformed
        //System.out.println("clicked Stop");
        StartStop = 0;
        DataFrame df = new DataFrame();
        df.Command = Config;
        df.Payload.speed = Integer.parseInt(TxtSpeed.getText());
        df.Payload.count = Integer.parseInt(TxtCount.getText());
        df.Payload.configuration = (byte) getConfig();
        df.Payload.start_stop = (byte) StartStop;
        CurrentFrame = df;
        Thread te = new Thread(new Runnable() {
        public void run()
        {
                TrainSimulatorApp.getApplication().getView().SendPacketRecieveResponse(CurrentFrame);
        }
        });
        te.start();
    }//GEN-LAST:event_BtnStopActionPerformed

    private int getConfig(){
        int conf = 0;
        if(this.headerOfPanel.equals(ConfigurationHeaders.FwdEntry)
                || this.headerOfPanel.equals(ConfigurationHeaders.Entry)
                || this.headerOfPanel.equals(ConfigurationHeaders.SSDAC_A)){
            conf = 1;
        }
        else if(this.headerOfPanel.equals(ConfigurationHeaders.Exit)
                || this.headerOfPanel.equals(ConfigurationHeaders.RvExit)
                || this.headerOfPanel.equals(ConfigurationHeaders.SSDAC_C)){
            conf = 2;
        }
        else if(this.headerOfPanel.equals(ConfigurationHeaders.MidPoint)
                || this.headerOfPanel.equals(ConfigurationHeaders.FwdExit)
                || this.headerOfPanel.equals(ConfigurationHeaders.SSDAC_B)){
            conf = 3;
        }
        else if(this.headerOfPanel.equals(ConfigurationHeaders.RvEntry)){
            conf = 4;
        }        
        return conf;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnStart;
    public javax.swing.JButton BtnStop;
    public javax.swing.JTextField TxtCount;
    public javax.swing.JTextField TxtSpeed;
    private javax.swing.JLabel entryType;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JSeparator jSeparator13;
    // End of variables declaration//GEN-END:variables

}
